### ISSUE TITLE
House of Rabbit - CTF Wiki

### ISSUE THREAD

**Issue by iromise** [ctf-wiki/comment#101]
https://ctf-wiki.github.io/ctf-wiki/pwn/linux/glibc-heap/house_of_rabbit/ 

 CTF Wiki

**Comment by lddd1234** [comment]
突然发现，malloc_consolidate在glibc 2.6后好像已经有check fastbin 的size 了。

**Comment by iromise** [comment]
没在意，之后有时间的话看一看。

**Comment by Demon-Wang** [comment]
这里有个疑问，POC1中

由于属于fastbin的chunk free掉之后并没有setfoot
在两次free之后  malloc大chunk导致consolidate

consolidate的实现中是从小fastbin中获取fast chunk 再到大的fastbin
free掉的两个chunk属于同一个bin,并且第一个执行consolidate的是chunk2
因为consolidate之前将所有的fastbins里面的chunk clear了chunk2 的pre_inuse位
所以chunk2会考虑后向合并chunk1 但是此时的chunk2的pre_size是0
那么
                    if (!prev_inuse(p)) {
                        prevsize = prev_size(p);
                        size += prevsize;
                        p = chunk_at_offset(p, -((long) prevsize));
                        unlink(av, p, bck, fwd);
                    }
会导致unlink本身，而chunk2的bk指针是0
不会造成unlink的 bk->fd 和 p的检测不通过吗？
难道又是我源码部分哪里看错了? 哭泣

难道是clear_fastchunks函数不仅清除了nextchunk的presize位，而且setfoot了?
不对呀unlink单链表肯定会出错呀。。

**Comment by iromise** [comment]
@Changochen 似乎当时这块是你来写的？

**Comment by Changochen** [comment]
@Demon-Wang 你可以仔细看看源代码。当一个fastbin chunk从fastbin中被抽取出来的时候就会变成unsortebin chunk ,不会出现你说的那么情况。
